# action.yml
name: 'TGS DMAPI Updater'
author: 'Cyberboss'
description: 'Updates TGS DMAPI in repositories'
inputs:
  header-path:
    description: 'Path to tgs.dm header file in the repository'
    required: true
  library-path:
    description: 'Path to the tgs directory in the repository'
    required: true
  github-token:
    description: 'GitHub token for cloning and pushing'
    required: false
    default: ${{ github.token }}
  repo-path:
    description: 'Path to the cloned repository on the branch to update'
    required: false
    default: '/github/workspace'
outputs:
  release-notes:
    description: 'The DMAPI release notes'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.header-path }}
  - ${{ inputs.library-path }}
  - ${{ inputs.github-token }}
  - ${{ inputs.repo-path }}
branding:
  icon: 'arrow-up-circle'
  color: 'green'
